### ISSUE TITLE
Project schedule week 9

### ISSUE THREAD

**Issue by MrM0nkey** [zervnet/pdns#10]
These goals should be reached until 20.06 12:15 pm.
- [x] Finish docker development envrioment scripts (benj-zen) 
- [x] Create a docker Pull request or ask for integration (MrM0key)
- [ ] Create a short Wiki [here](https://github.com/PowerDNS/pdns/wiki) for the docker development envrioment #8
- [x] Finish Put/Patch Tests (zervnet) 
- [ ] Create all docker backend files #7 (everybody)
- [ ] Test backends for the add Key #4
- [x] Add POST api-spec #5 (MrM0nkey)
- [x] What is csk ? (MrM0nkey)

Edit this Issue to take a task. Set your name behind a task.
