### ISSUE TITLE
Project schedule week 10

### ISSUE THREAD

**Issue by MrM0nkey** [zervnet/pdns#11]
These goals should be reached until 20.06 12:15 pm.
- [x] Create a good Wiki [here](https://github.com/PowerDNS/pdns/wiki) for the docker development envrioment #8
- [ ] Create all docker backend files #7 (everybody)
- [x] Test backends for the add Key #4
- [x] Change 501 error in cryptokeys.
- [ ] Add backend test solution to Docker
- [ ] Submit big PR

Edit this Issue to take a task. Set your name behind a task. I would recommend to create a new issue when working on an goal.

**Comment by MrM0nkey** [comment]
I take a look at https://github.com/PowerDNS/pdns/wiki/Regression-tests an try to get things done.

**Comment by MrM0nkey** [comment]
Test backends for the add Key #4. I am not able to do it this week.

**Comment by taudor** [comment]
Changed 501 error to 405 error (method not allowed). See 9f03d96
