### ISSUE TITLE
TODO for PR

### ISSUE THREAD

**Issue by taudor** [zervnet/pdns#13]
- api_spec.md
- [x] 200 OK
- [x] json formatierung
- [x] change 'CryptoKey' to 'Cryptokey' to be consistent (or vise versa in ws-auth.cc)
- dnsseckeeper.hh
- [x] 165/166 change return of addKey to bool and add &key_id as parameter for addKey
- dbdnsseckeeper.cc
- [x] 97 throw runtime_error("Wrong bit size!"); more specific error
- pdns/ws-auth.cc
- [x] 564 wrong intend
- pdns/ws-auth.cc
- [x] GET/PUT/DELETE Code redundancy / consistent return codes
- [x] 553 whitespace
- [x] 598 why do you have inquireKeyId in the param list and then check for key_id in req->parameters too?
- [x] 758 PUT returns 204
- [x] 606 DELETE change to 200 no body
- [x] 633Change 'can't'
- [x] 631/637 No '!'
- [x] 668 delete tmpAlgo and assign into algorithm
- [x] 676 space try' '{
- [x] 700 add &
- [x] 701 key format could not be paresed. please make sure your key is correct
- [x] 674 insert else and throw exception for wrong/unknown algorithm else if (providedAlgo != NULL)
- [x] 732 aufräumen
- [x] 685 POST change behavior in case of: just content given -> change api_spec
- [x] 780 space
- docs/markdown/httpapi/api_spec.md
- [x] POST change additional fiels in case 'content == null'
- [x] 732 grammar issue
- [x] 717 Change to 200
- [x] 738 Change json type
- regression-tests.api/test_cryptokeys.py
- [x] 26 grammar issues
- [x] 26ff change to test just return 200
- [x] split the test function per each comment that you wrote.
- [x] change 'Cryptokeys.zone' to 'self.zone'
- [x] 43 change to 'self.assertNotIn(zonename, out)'
- [x] 53 just 200
- [x] 85 grammar
- [x] 258 what's z for?
- pdns/pdnsutil.cc
- [x] 1748 delete '!'
- modules/bindbackend/binddnssec.cc
- [x] 332 add more context to exception (failed to execute last query)
- pdns/backends/gsql/gsqlbackend.cc
- [x] 667ff missing ASSERT_ROW_COLUMNS() to prevent reading out of bound (custom queries !!!)

**Comment by taudor** [comment]
first number is the linenumber in the code

**Comment by taudor** [comment]
I'm working on ws-auth.cc
