### ISSUE TITLE
Update Rest Api Documentation

### ISSUE THREAD

**Issue by MrM0nkey** [zervnet/pdns#5]
Update the [rest api documentation](https://github.com/PowerDNS/pdns/blob/master/docs/markdown/httpapi/api_spec.md#url-apiv1serversserver_idzoneszone_namecryptokeyscryptokey_id) for the features:
- [x] #3 Rest API Feature: cryptokey_id PUT
- [x] #2 Rest API Feature: cryptokeys POST
- [x] #1 Rest API Feature: Create the possibility to delete cryptokeys by id using rest api.

Specify this features in a way that goes conform to powerdns documentation.

**Comment by MrM0nkey** [comment]
@zervnet case 2 in comment:

>   This method handles PUT (execute) requests for URL /api/v1/servers/:server_id/zones/:zone_name/cryptokeys/:cryptokey_id .
>   It de/activates a key from :zone_name specified by :cryptokey_id.
>   Server Answers:
>   Case 1: zone_name not found
>        The server returns 404 Not Found
>   Case 2: invalid JSON data
>        The server returns 400 Bad Request
>   Case 3: the backend returns true on de/activation. This means the key is de/active.
>        The server returns 200 OK
>   Case 4: the backend returns false on de/activation. An error occoured.
>        The sever returns 422 Unknown Status with message "Could not de/activate Key: :cryptokey_id in Zone: :zone_name"

from https://github.com/zervnet/pdns/blob/feature_rest_api_cryptokeys_post/pdns/ws-auth.cc should be deleted because the put function does not invoke the response.
